os: Visual Studio 2015

version: 0.1.0.{build}

platform: x64

clone_folder: c:\gopath\src\github.com\kivutar\go-playthemall

environment:
  GOPATH: c:\gopath
  CC: gcc.exe

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;C:\MinGW\bin;%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - gcc --version
  - go env

build_script:
  - go get -t .
  - go build