name: CD

on:
  release:
    types: [created]

defaults:
  run:
    shell: bash

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-go@v2
      - run: sudo apt-get install libopenal-dev xorg-dev libgl1-mesa-dev -y --allow-unauthenticated
      - run: OS=Linux ARCH=x86_64 VERSION=${{ github.event.release.tag_name }} make tar

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: Ludo-Linux-x86_64-${{ github.event.release.tag_name }}.tar.gz
          asset_name: Ludo-Linux-x86_64-${{ github.event.release.tag_name }}.tar.gz
          asset_content_type: application/gzip

build_linux_arm:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-go@v2
    - run: sudo apt-get install binutils-multiarch
    - run: sudo dpkg --add-architecture armhf
    - run: sudo echo "" > /etc/apt/sources.list.d/ludo.list
    - run: sudo echo "deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu/ bionic main restricted universe multiverse" >> /etc/apt/sources.list.d/ludo.list
    - run: sudo echo "deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports bionic main restricted universe multiverse" >> /etc/apt/sources.list.d/ludo.list
    - run: sudo echo "deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu/ bionic-updates main restricted universe multiverse" >> /etc/apt/sources.list.d/ludo.list
    - run: sudo echo "deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports bionic-updates main restricted universe multiverse" >> /etc/apt/sources.list.d/ludo.list
    - run: sudo echo "deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse" >> /etc/apt/sources.list.d/ludo.list
    - run: sudo echo "deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports bionic-backports main restricted universe multiverse" >> /etc/apt/sources.list.d/ludo.list
    - run: sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 6B05F25D762E3157
    - run: sudo apt-get update -q
    - run: sudo apt-get install libc6-dev:amd64 libc6-dev:armhf gcc-arm-linux-gnueabihf libopenal-dev:armhf libgl1-mesa-dev:armhf libxcursor-dev:armhf libxrandr-dev:armhf libxinerama-dev:armhf libxi-dev:armhf -y --allow-unauthenticated
    - run: export PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig/
    - run: GOOS=linux GOARCH=arm GOARM=7 CGO_ENABLED=1 CC=arm-linux-gnueabihf-gcc go build -v

  build_osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-go@v2
      - run: echo "/Users/runner/go/bin" >> $GITHUB_PATH
      - run: go get golang.org/x/lint/golint
      - run: go get honnef.co/go/tools/cmd/staticcheck
      - run: brew install openal-soft
      - run: echo ${{ secrets.OSXCERT }} | base64 --decode > dev.p12
      - run: security create-keychain -p github build.keychain
      - run: security default-keychain -s build.keychain
      - run: security unlock-keychain -p github build.keychain
      - run: security import dev.p12 -k build.keychain -P ${{ secrets.OSXCERTPASS }} -T /usr/bin/codesign && rm dev.p12
      - run: security set-key-partition-list -S "apple-tool:,apple:,codesign:" -s -k github build.keychain
      - run: OS=OSX ARCH=x86_64 VERSION=${{ github.event.release.tag_name }} make dmg

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: Ludo-OSX-x86_64-${{ github.event.release.tag_name }}.dmg
          asset_name: Ludo-OSX-x86_64-${{ github.event.release.tag_name }}.dmg
          asset_content_type: application/apple-diskimage

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-go@v2
      - run: choco install wget make --ignore-checksums
      - run: wget http://static.kivutar.me/openal-soft-1.19.0-bin.zip
      - run: wget https://github.com/electron/rcedit/releases/download/v1.1.1/rcedit-x64.exe
      - run: 7z x openal-soft-1.19.0-bin.zip -o/c/openal-soft-1.19.0-bin
      - run: echo "CGO_CFLAGS=-I/c/openal-soft-1.19.0-bin/include/" >> $GITHUB_ENV
      - run: echo "CGO_LDFLAGS=-L/c/openal-soft-1.19.0-bin/build/Release/" >> $GITHUB_ENV
      - run: cp /c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/x86_64-w64-mingw32/lib/libwinpthread* .
      - run: cp /c/openal-soft-1.19.0-bin/build/Release/OpenAL32.* .
      - run: cp /c/Windows/System32/VCRUNTIME140.dll .
      - run: mkdir -p ./Ludo-Windows-x86_64-${{ github.event.release.tag_name }}/
      - run: cp *.dll ./Ludo-Windows-x86_64-${{ github.event.release.tag_name }}/
      - run: OS=Windows ARCH=x86_64 VERSION=${{ github.event.release.tag_name }} make zip

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: Ludo-Windows-x86_64-${{ github.event.release.tag_name }}.zip
          asset_name: Ludo-Windows-x86_64-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
